version: '3'
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

  service-one:
    image: nginx
    volumes:
      - ./service-one/:/usr/share/nginx/html

  service-two:
    image: nginx
    volumes:
      - ./service-two/:/usr/share/nginx/html